// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: services/mapper.proto

package services

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunMapInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    int32  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Fn        string `protobuf:"bytes,2,opt,name=fn,proto3" json:"fn,omitempty"`
	NReducers int32  `protobuf:"varint,3,opt,name=nReducers,proto3" json:"nReducers,omitempty"`
	FileName  string `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileData  []byte `protobuf:"bytes,5,opt,name=fileData,proto3" json:"fileData,omitempty"`
}

func (x *RunMapInput) Reset() {
	*x = RunMapInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunMapInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMapInput) ProtoMessage() {}

func (x *RunMapInput) ProtoReflect() protoreflect.Message {
	mi := &file_services_mapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMapInput.ProtoReflect.Descriptor instead.
func (*RunMapInput) Descriptor() ([]byte, []int) {
	return file_services_mapper_proto_rawDescGZIP(), []int{0}
}

func (x *RunMapInput) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RunMapInput) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *RunMapInput) GetNReducers() int32 {
	if x != nil {
		return x.NReducers
	}
	return 0
}

func (x *RunMapInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RunMapInput) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type InitReduceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ports []string `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *InitReduceInput) Reset() {
	*x = InitReduceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mapper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitReduceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReduceInput) ProtoMessage() {}

func (x *InitReduceInput) ProtoReflect() protoreflect.Message {
	mi := &file_services_mapper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReduceInput.ProtoReflect.Descriptor instead.
func (*InitReduceInput) Descriptor() ([]byte, []int) {
	return file_services_mapper_proto_rawDescGZIP(), []int{1}
}

func (x *InitReduceInput) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mapper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_services_mapper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_services_mapper_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KvPairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*KeyValue `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *KvPairs) Reset() {
	*x = KvPairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_mapper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPairs) ProtoMessage() {}

func (x *KvPairs) ProtoReflect() protoreflect.Message {
	mi := &file_services_mapper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPairs.ProtoReflect.Descriptor instead.
func (*KvPairs) Descriptor() ([]byte, []int) {
	return file_services_mapper_proto_rawDescGZIP(), []int{3}
}

func (x *KvPairs) GetData() []*KeyValue {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_services_mapper_proto protoreflect.FileDescriptor

var file_services_mapper_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b,
	0x01, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x66, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x0f,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x4b, 0x76, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x8d, 0x01, 0x0a,
	0x0d, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39,
	0x0a, 0x06, 0x52, 0x75, 0x6e, 0x4d, 0x61, 0x70, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6f, 0x62, 0x79,
	0x73, 0x63, 0x6f, 0x6f, 0x62, 0x2f, 0x6d, 0x61, 0x70, 0x2d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_services_mapper_proto_rawDescOnce sync.Once
	file_services_mapper_proto_rawDescData = file_services_mapper_proto_rawDesc
)

func file_services_mapper_proto_rawDescGZIP() []byte {
	file_services_mapper_proto_rawDescOnce.Do(func() {
		file_services_mapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_mapper_proto_rawDescData)
	})
	return file_services_mapper_proto_rawDescData
}

var file_services_mapper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_mapper_proto_goTypes = []interface{}{
	(*RunMapInput)(nil),     // 0: services.RunMapInput
	(*InitReduceInput)(nil), // 1: services.InitReduceInput
	(*KeyValue)(nil),        // 2: services.KeyValue
	(*KvPairs)(nil),         // 3: services.KvPairs
	(*empty.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_services_mapper_proto_depIdxs = []int32{
	2, // 0: services.KvPairs.data:type_name -> services.KeyValue
	0, // 1: services.MapperService.RunMap:input_type -> services.RunMapInput
	1, // 2: services.MapperService.InitReduce:input_type -> services.InitReduceInput
	4, // 3: services.MapperService.RunMap:output_type -> google.protobuf.Empty
	4, // 4: services.MapperService.InitReduce:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_mapper_proto_init() }
func file_services_mapper_proto_init() {
	if File_services_mapper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_mapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunMapInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_mapper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitReduceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_mapper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_mapper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvPairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_mapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_mapper_proto_goTypes,
		DependencyIndexes: file_services_mapper_proto_depIdxs,
		MessageInfos:      file_services_mapper_proto_msgTypes,
	}.Build()
	File_services_mapper_proto = out.File
	file_services_mapper_proto_rawDesc = nil
	file_services_mapper_proto_goTypes = nil
	file_services_mapper_proto_depIdxs = nil
}
